language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - export CLASS_DOC_SOURCE_URI=https://github.com/NetCommons3/NetCommons3.git
  - for s in pre main post; do wget https://raw.githubusercontent.com/topaz2/chef_boilerplate_php/master/files/default/tools/build/travis/app_docs/$s.sh; chmod +x $s.sh; done
  - . ./pre.sh

script:
  - travis_wait . ./main.sh

after_script:
  - . ./post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
