language: php

php:
  - 5.4
  - 5.5

before_script:
  - sudo aptitude update
  - sudo aptitude install python-setuptools
  - sudo easy_install sphinx
  - sudo easy_install sphinxcontrib-phpdomain
  - mkdir -p build/logs
  - pear channel-discover pear.phpdoc.org
  - pear install phpdoc/phpDocumentor
  - phpenv rehash
  - set +H

script:
  - cd $TRAVIS_BUILD_DIR/sphinx && make html

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
      - nii@m0n0m0n0.com
    on_success: never  # default: change
    on_failure: always # default: always
