language: php

php:
  - 5.6

env:
  matrix:
    - PATTERN="ABCD QRST"
    - PATTERN="EFGH UVWX"
    - PATTERN="IJKL YZ"
    - PATTERN="MNOP"
  global:
    - secure: "S9QtTDWb49VduRwS3xCgFSdAAA/xyyccW6W88e0OF0z8zRTO6MSkSQqSh7GDCPoc3mOhMEfPEszZ04jSPYDZToEA2m6O1VhFWKnXJhetnIWYzQhq9gUeXcONVp0PvSzEkrarzFY9Xu1lrERX1ZSpwWkvki+jyLJo/7brpS8ZDXk="

sudo: required

before_script:
  - export CLASS_DOC_SOURCE_URI=https://github.com/NetCommons3/NetCommons3.git
  - export CLASS_DOC_SOURCE_ROOT=`dirname $TRAVIS_BUILD_DIR`/build/NetCommons3
  - export APP_ROOT=$CLASS_DOC_SOURCE_ROOT/app
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/build/NetCommons3Docs
  - export NETCOMMONS3DOCS=NetCommons3/NetCommons3Docs
  - cd $TRAVIS_BUILD_DIR
  - for s in pre main main2 main3 post; do wget https://raw.githubusercontent.com/$NETCOMMONS3DOCS/$TRAVIS_BRANCH/tools/build/app/travis/$s.sh; chmod +x $s.sh; done
  - . ./pre.sh

script:
  - cd $TRAVIS_BUILD_DIR; . ./main.sh
  - cd $TRAVIS_BUILD_DIR; . ./main2.sh "[ABCD]" "ABCD QRST"
  - cd $TRAVIS_BUILD_DIR; . ./main2.sh "[EFGH]" "EFGH UVWX"
  - cd $TRAVIS_BUILD_DIR; . ./main2.sh "[IJKL]" "IJKL YZ"
  - cd $TRAVIS_BUILD_DIR; . ./main2.sh "[MNOP]" "MNOP"
  - cd $TRAVIS_BUILD_DIR; . ./main2.sh "[QRST]" "ABCD QRST"
  - cd $TRAVIS_BUILD_DIR; . ./main2.sh "[UVWX]" "EFGH UVWX"
  - cd $TRAVIS_BUILD_DIR; . ./main2.sh "[YZ]" "IJKL YZ"
  - cd $TRAVIS_BUILD_DIR; . ./main3.sh

after_script:
  - cd $TRAVIS_BUILD_DIR; travis_wait . ./post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
